# Generated by Django 3.0.7 on 2021-08-27 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210827_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Class')),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
