# Generated by Django 3.0.7 on 2021-08-27 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210827_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classroom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='todo',
            new_name='classroom',
        ),
    ]
