# Generated by Django 3.0.7 on 2021-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(null=True, to='api.Student'),
        ),
    ]
