# Generated by Django 3.0.7 on 2021-08-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assignment_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
    ]
