# Generated by Django 3.0.7 on 2021-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210828_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.BooleanField(choices=[(True, 'Graded'), (False, 'Ungraded')]),
        ),
    ]
