# Generated by Django 3.0.7 on 2021-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210828_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='type',
        ),
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.BooleanField(choices=[(True, 'Graded'), (False, 'Ungraded')], default=False),
        ),
    ]
