# Generated by Django 3.0.7 on 2021-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_classroom_classroom_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_color',
            field=models.BooleanField(choices=[('0', 'Blue-theme'), ('1', 'Red-theme'), ('2', 'Violet-theme'), ('3', 'Green-theme')], default=False),
        ),
    ]
